spring:
  profiles:
    active: local
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,wall,slf4j
  jpa:
    show-sql: true
    hibernate :
      ddl-auto : update
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML5

logging:
  config: classpath:logback-spring.xml
logging.level.org.springframework.boot.autoconfigure: ERROR


security:
  basic:
    enabled: false
