spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3307/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.enable_lazy_load_no_trans: true